# provider: 
# api_key: 
# base_url: 
# model_name: 
# temperature: 0.0
# max_tokens: 1024

provider: openai
base_url: http://127.0.0.1:1234/v1
model_name: qwen2.5-coder-1.5b-instruct
# base_url: https://api.openai.com/v1
# model_name: gpt-4o-mini

temperature: 0.0
max_tokens: 256